### ISSUE TITLE
章节18.7.1 内容未说清楚

### ISSUE THREAD

**Issue by LawrenceHan** [tangqiaoboy/iOS-Pro#5]
##### 2.脚本在哪里运行没说清楚

> 我的理解是，应该放在xcode里运行该脚本吧，这样每次build都会删除。
### 截图

![messages image 1440450885](https://cloud.githubusercontent.com/assets/7960810/5995652/0af4b9aa-aad4-11e4-87d6-b27e90bdeee0.png)

**Comment by LawrenceHan** [comment]
@tangqiaoboy please check this one, thanks. :dancers:

**Comment by tangqiaoboy** [comment]
多次界面改版之后，想知道自己的工程中有哪些图片资源并没有使用？这里给大家提供一个小脚本，可以删除未使用的图片资源。(使用前需要先`brew install ack`，安装一个名为`ack`命令行工具)：

```
for i in `find . -name "*.png" -o -name "*.jpg"`; do
    file=`basename -s .jpg "$i" | xargs basename -s .png | xargs basename -s @2x`

    result=`ack -i "$file"`
    if [ -z "$result" ]; then
        echo "$i"
        # 如果需要，可以直接执行删除：
        # rm "$i"
    fi
done
```

**Comment by tangqiaoboy** [comment]
好奇怪，我的书稿是好的，排版之后却少了一个后括号。不知道出版社为什么会漏掉。囧啊。。。。

代码是 shell 的脚本，不需要每次都执行，我一般是另外保存成一个 .sh 的文件，需要的时候执行一下就行了。因为也不会老出现这种未使用的图片资源。

**Comment by tangqiaoboy** [comment]
谢谢你的反馈，我改进一下书中的描述。

**Comment by LawrenceHan** [comment]
:smile: 好的，这个issue可以关了
