### ISSUE TITLE
Reveal连接模拟器方式失效

### ISSUE THREAD

**Issue by AzenXu** [tangqiaoboy/iOS-Pro#9]
巧兄，按照书中方式关联到reveal，并不能在reveal中看到想要调试的iOS程序界面... 是连接方式有变化吗？

**Comment by tangqiaoboy** [comment]
第34页，用reveal连接真机调试章节，由于苹果的编译器升级，加载reveal的步骤更多了，详细的见：http://support.revealapp.com/kb/getting-started/integrating-reveal-add-reveal-to-your-xcode-project
